name: Run Tests

on:
  pull_request:
    branches:
      - main # Adjust the branch name as needed
      - develop # Add additional branches if necessary

jobs:
  test:
    name: Run npm test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
